#define KEY_MEDIA_PLAYPAUSE 0xe8
#define KEY_MEDIA_STOPCD 0xe9
#define KEY_MEDIA_PREVIOUSSONG 0xea
#define KEY_MEDIA_NEXTSONG 0xeb
// #define KEY_MEDIA_EJECTCD 0xec
#define KEY_MEDIA_VOLUMEUP 0xed
#define KEY_MEDIA_VOLUMEDOWN 0xee
#define KEY_MEDIA_MUTE 0xef
#define KEY_MEDIA_COFFEE 0xf9

#define SWITCH_PIN 0
#define PAUSE_BUTTON_PIN 16
#define FF_BUTTON_PIN 17
#define RW_BUTTON_PIN 18
#define ENCODER_A_PIN 12
#define ENCODER_B_PIN 13
#define ENCODER_CLICK_PIN 11